---
title: "Topic X: Reproducible Example of Randomization Error"
tutorial:
  id: "ReprEx.TopicX.AppliedStats"
  version: 1.0
output: 
  learnr::tutorial:
    progressive: TRUE
    
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(learnr)
library(gradethis)

diamonds <- diamonds
diamonds <- data.frame(diamonds)

rows1 <- c(10, 29, 48, 228, 97, 643, 774, 283)
rows2 <- c(48, 758, 890, 334, 536, 364, 65, 554)
rows3 <- c(454, 8, 646, 354, 856, 53, 76)

diamonds$region <- sample(c(1,2,3,4,5), prob = c( 0.11, .02 , 0.65, 0.20, .02), nrow(diamonds), replace = TRUE)
diamonds$region <- as.factor(diamonds$region)

samples <- data.frame(Sample_One = diamonds$carat[rows1], Sample_Two = diamonds$carat[rows2], Sample_Three = c(diamonds$carat[rows3], 5))

cut.samples <- data.frame(Sample_One = diamonds$cut[rows1], Sample_Two = diamonds$cut[rows2], Sample_Three = diamonds$cut[c(rows3, 753)])

tutorial_options(exercise.timelimit = 60, exercise.checker = gradethis::grade_learnr)
```


# A Reproducible Example

```{r echo = FALSE, eval = TRUE}
samples
```

```{r print-samples, exercise = TRUE}

```
